[package]
name = "lilarena"
version = "0.1.0"
edition = "2021"
publish = false
description = "handle some of the load of lichess.org/tournament"
homepage = "https://lichess.org/tournament"
repository = "https://github.com/ornicar/lilarena"
readme = "README.md"
license = "AGPL-3.0+"
categories = ["games"]
keywords = ["chess", "lichess"]

[dependencies]
axum = "0.4"
clap = { version = "3.0.0-rc.4", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
moka = { version = "0.6.2", features = ["future"] }
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.2", features = ["set-header"] }
